---
- include: setup.yml

- name: Configure elasticsearch.yml.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750
  notify: restart elasticsearch

- name: Create custom storage directory.
  file:
    path: "{{ elasticsearch_custom_storage_path }}"
    state: directory
    owner: root
    group: elasticsearch
    mode: 0770
  when: elasticsearch_custom_storage_enabled
  notify: restart elasticsearch

- meta: flush_handlers

- name: Ensure Elasticsearch is started and enabled on boot.
  systemd:
    name: elasticsearch
    state: started
    enabled: "{{ elasticsearch_enabled_on_boot }}"
    daemon_reload: yes

- name: Make sure Elasticsearch is running before proceeding.
  wait_for:
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 300
