---
- include: setup.yml

- name: Configure Elasticsearch.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750
  notify: restart elasticsearch

- name: Ensure Elasticsearch is started and enabled on boot.
  systemd:
    name: elasticsearch
    state: started
    enabled: "{{ elasticsearch_enabled_on_boot }}"
    daemon_reload: yes

- name: Make sure Elasticsearch is running before proceeding.
  wait_for:
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 300
